server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Annonce
          uri: http://localhost:8081
          predicates:
            - Path=/annonces/**
        - id: Reservation
          uri: http://localhost:8556
          predicates:
            - Path=/reservations/**
        - id: MicroserviceMessagerie
          uri: http://localhost:8085
          predicates:
            - Path=/api/messages/**

